### ISSUE TITLE
TF Refactor 1: Consolidate dev and main branches

### ISSUE THREAD

**Issue by cpcundill** [digital-land/technical-documentation#190]
**Overview**

Consolidate the dev and main branches of the digital-land-infrastructure repository in preparation for structural changes to the Terraform code.  

This ticket represents a key foundational piece of work to facilitate refactoring of Terraform; the need to consolidate the dev and main branches.  Without such, refactoring would effectively have to be performed twice; once on the dev branch and then again on the main branch.

**Background**

Following the [design work for refactoring our Terraform code & state](https://github.com/digital-land/technical-documentation/issues/74), a [design proposal for Infrastructure Code Disaggregation](https://github.com/digital-land/technical-documentation/discussions/181) was published.

**Acceptance Criteria/Tests**

- Environmental differences are captured in configuration vars rather than diverse codebases
- The main branch can be used to apply Terraform to all environments; dev, staging and prod

**Tech Approach**

- Create feature branch with main as the target
- Merge dev branch manually - ensuring environment differences are controlled via configuration vars
- Make changes in task branches targeting the feature branch - name for task branches: task/190-descriptive-name
- Raise merge request

**Resourcing & Dependencies**

- Required before all TF Refactor tickets

**Tasks**

- [x] Merge/close any existing PRs prior to refactoring (Chris)
- [x] Create merge branch with main as target - branch name "feature/190-consolidate-dev-main-branches" (Chris)
- [x] Merge deployment approval changes from dev (Ernest)
- [x] Merge or delete database provisioner work from dev - confirm with Owen (Chris)
- [x] Settle AWS provider version to use as baseline (in root and all modules) (Ernest)
- [x] Settle GitHub provider version to use as baseline (in root and all modules) (Chris)
- [x] Remove Async task CPU increase from dev (Chris)
- [x] Merge or delete Airflow differences (Chris)
- [x] Merge System tag changes from dev (Ernest)
- [x] Merge or delete Canary smoke test differences (Chris)
- [x] Delete old Parquet changes (Ernest)
- [x] Cleanup subdomain module and preserve state of main branch (Chris)
- [x] Introduce Airflow variable for startup script (Chris)
- [x] Introduce Heroku App variable for sub domain (Ernest)
- [x] Align environment variable files on dev with main (Ernest) 
- [x] Update Terraform version in dev for module template (Ernest)
- [x] Apply Terraform from  "feature/190-consolidate-dev-main-branches" to development environment and merge feature branch to main (Ernest)
- [x]  Delete dev branch (Chris & Ernest)
